[tool.poetry]
name = "commandcenter"
version = "0.1.0"
description = ""
authors = ["Denis Bobela <youtipie@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
